use_frameworks!

platform :ios, '8.0'

target 'ESTVLiveSdk4Phone_Example' do
  pod 'ESTVLiveSdk4Phone', :path => '../'

  target 'ESTVLiveSdk4Phone_Tests' do
    inherit! :search_paths

    
  end
end
